### ISSUE TITLE
Support for IMAP

### ISSUE THREAD

**Issue by Paxa** [rails/actionmailbox#14]
Any plans to support for IMAP?
In my case we want to keep customer's data in gmail and not share with other companies.

We use 2 IMAP connection in separate ruby threads and broker between them: first one run `IDLE` command and send command to broker, another one wait for broker's command and check for new emails, works well so far

p.s. gmail api can not be used because access token have short lifetime

**Comment by georgeclaghorn** [comment]
We don’t have any plans to support IMAP at the moment. Please do investigate!

Keep in mind that an implementation requiring long-running processes or threads wouldn’t be a good fit for inclusion in Rails. If you pursue this, I’d suggest adding a Rake task (in the manner of `action_mailbox:ingress:postfix`) that consumes emails from an IMAP account and POSTs them to an ingress controller. Those who want to use IMAP would set up a cron job to run the Rake task every minute or so.
