### ISSUE TITLE
Should the "postfix" ingress rather be called a "pipe" ingress?

### ISSUE THREAD

**Issue by martinvonwittich** [rails/actionmailbox#15]
Just a quick suggestion: from what it looks like, the "postfix" ingress seems to work like a generic pipe; this should work fine with any MTA that is able to pipe mail to external processes, for example Exim too: https://www.exim.org/exim-html-current/doc/html/spec_html/ch-the_pipe_transport.html

Wouldn't this be therefore better named as "pipe" instead of "postfix"?

**Comment by georgeclaghorn** [comment]
It specifically generates output in a format that Postfix recognizes. Exim’s pipe transport doesn’t appear to honor an SMTP enhanced status code at the beginning of `stdout` when the invoked command exits with status code `1`, so the Postfix ingress is not generic as currently implemented.

Please feel free to investigate adding proper support for Exim. In theory, separate Rake tasks for Postfix and Exim could share a single [relayer class](https://github.com/rails/actionmailbox/blob/dcddff1d2d0c695318670686a27429a76f20ae03/lib/action_mailbox/postfix_relayer.rb) and [ingress controller](https://github.com/rails/actionmailbox/blob/dcddff1d2d0c695318670686a27429a76f20ae03/app/controllers/action_mailbox/ingresses/postfix/inbound_emails_controller.rb), but they’d each need to meet the status code and output expectations of the corresponding MTA’s pipe transport. (I believe Postfix follows the same exit status conventions as Exim, but we prefer to use enhanced status codes where they’re supported.)
